### ISSUE TITLE
liquid variables are not being interpreted 

### ISSUE THREAD

**Issue by cdeath** [sdumetz/jekyll-inline-svg#2]
`{% svg "{{company.logo-color}}" %}`

i get this error when running jekyll:
  Liquid Exception: No such file or directory @ rb_sysopen - /Users/whatever/Sites/site/{{company.logo-color}} in /_layouts/page.html

am i missing something?

**Comment by sdumetz** [comment]
It's done by the `lookup_variable` function from jekyll. I know it misses some things but can't really do anything about it unless I replace it with some more advanced function like https://github.com/envygeeks/liquid-tag-parser .
Afaik it *should* work as-is in this case though. I'll look into it when I have some time.

**Comment by cdeath** [comment]
it's the hyphens... it doesn't like them.

**Comment by sdumetz** [comment]
I made a change in https://github.com/sdumetz/jekyll-inline-svg/commit/2f42a676062fca257b49947b29521db058fb3e7f
I've just done a quick unit-test validarion. I'll test it on my site later to check if it doesn't break anything.
Could you test it on your end just to be sure? If it works I'll update the Gem.

**Comment by sdumetz** [comment]
V1.1.3 published with this fix.

Thanks for reporting.

**Comment by cdeath** [comment]
sorry i missed your request. i ended up changing the variable name. but i will test this version against my code. thank you!
